//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection
    {
        public System.DateTime Expiredate { get; set; }
        public string Description { get; set; }
        public string Assignto { get; set; }
    }
}
